# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartellaSociale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucina',
            name='oggi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='oggi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='oggi',
            field=models.DateField(blank=True, null=True, verbose_name='data prima accoglienza'),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='scadtessmen',
            field=models.DateField(blank=True, null=True, verbose_name='scadenza'),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='ssnscad',
            field=models.DateField(blank=True, null=True, verbose_name='scadenza'),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='stpscad',
            field=models.DateField(blank=True, null=True, verbose_name='scadenza'),
        ),
    ]
