# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartellaSociale', '0002_auto_20170408_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartella Sociale Avvocati',
        ),
        migrations.CreateModel(
            name='Cartella Sociale Avvocato',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cartelle Sociale Avvocati',
                'proxy': True,
            },
            bases=('cartellaSociale.utenti',),
        ),
        migrations.AlterModelOptions(
            name='accoglienza residenziale',
            options={'verbose_name_plural': 'Accoglienze Residenziali'},
        ),
        migrations.AlterModelOptions(
            name='cartella sociale',
            options={'verbose_name_plural': 'Cartelle Sociali'},
        ),
        migrations.AlterField(
            model_name='risorse',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='liv05_oretit_refapa',
            field=models.CharField(blank=True, db_column='Liv05_oretit/refapa', max_length=30, null=True, verbose_name='Ore settimanali (titolare/referente apa)'),
        ),
    ]
