# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartellaSociale', '0004_auto_20170408_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donazioni',
            name='citta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='eta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='età'),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita'),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='donazioni',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='nasc',
            field=models.DateField(blank=True, default='gg/mm/aaaa', null=True, verbose_name='nato il'),
        ),
        migrations.AlterField(
            model_name='utenti',
            name='telef',
            field=models.CharField(max_length=16, null=True, verbose_name='telefono'),
        ),
    ]
