# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartellaSociale', '0005_auto_20170410_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utenti',
            name='nasc',
            field=models.DateField(blank=True, null=True, verbose_name='nato il'),
        ),
    ]
